name: CI Pipeline

# Trigger the workflow on every push to any branch
on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Set up an in-memory MongoDB instance for testing
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match your project’s Node version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        env:
          MONGODB_URI: 
          JWT_SECRET: 
        run: npm test

      # Optional: Add a build step if you need to compile TypeScript
      - name: Build project
        run: npm run build